 import Head from "next/head";
import Components from "../components/basic/AllComponents";
import Cards from "../components/basic/cards";
export default function Basic() {
  return (
    <div>
      <Head>
        <title>Basic Components - Free Nextjs Ui Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br/>
      <h1>Body ownership and Touching</h1>
      <div style={
        {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-evenly",
            flexWrap: "wrap",
            alignItems: "center",
        }
      }>

      <Cards question={"Who has Right Over Your Body ?"} butext={"Show Answer"}/>
      <Cards question={"How to identify Bad Touch ?"} butext={"Show Answer"}/>
      <Cards question={"How to react to the Bad Touch ?"} butext={"Show Answer"}/>
      </div>
      <br/>
      <h1>Our Body + Puberty</h1>
      <div style={
        {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-evenly",
            flexWrap: "wrap",
            alignItems: "center",
        }
      }>

      <Cards question={"Understand Male-Female anatomy"} butext={"Show Answer"}/>
      <Cards question={"What is Hitting puberty mean?"} butext={"Show Answer"}/>
      <Cards question={"What is Pregnancy and what happens in it?"} butext={"Show Answer"}/>
      
      </div>
      <br/>
      <h1>How Children are born?</h1>
      <div style={
        {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-evenly",
            flexWrap: "wrap",
            alignItems: "center",
        }
      }>

      <Cards question={"Myths Around child birth"} butext={"Show Answer"}/>
      <Cards question={"What happens pre-pregnancy?"} butext={"Show Answer"}/>
      <Cards question={"What happens during pregnan cy?"} butext={"Show Answer"}/>
      
      </div>
    </div>
  );
}
